global:
  joints_count: 7.0
  arm_topic: /robot_arm
  imu_receive_topic: /imu/data_raw
  yolo_object_offset_receive_topic: /yolo/object/offset
  angle_step: 5.0  # Amount to increase/decrease angle by with keyboard input
pybullet:
  urdf_name: target.urdf
  gui: true # true or false
  view_world: false # true or false
  initial_height : 0.195
  controllable_joints : 5.0
  end_eff_index: 10.0
  time_step: 1e-3
joints:
  0:
    min_angle: -360.0
    max_angle: 360.0
  1:
    min_angle: -360.0
    max_angle: 360.0
  2:
    min_angle: -360.0
    max_angle: 360.0
  3:
    min_angle: -360.0
    max_angle: 360.0
  4:
    min_angle: -360.0
    max_angle: 360.0
  5:
    min_angle: -360.0
    max_angle: 360.0
  6:
    min_angle: -360.0
    max_angle: 360.0
joints_reset:
  0: 0.0
  1: -20.0
  2: 90.0
  3: 20.0
  4: -90.0
  5: 0.0
  6: 0.0

